-- Add detailed company information fields to jobsea_companies table
ALTER TABLE public.jobsea_companies
ADD COLUMN description TEXT,
ADD COLUMN mission TEXT,
ADD COLUMN values TEXT[],
ADD COLUMN preferred_profile TEXT,
ADD COLUMN salary_range TEXT;

-- Insert 20+ diverse finance companies with detailed information
INSERT INTO public.jobsea_companies (
  name, linkedin_url, logo, sector, headcount, open_jobs, 
  glassdoor_rating, hiring_velocity, geography, 
  description, mission, values, preferred_profile, salary_range
) VALUES 
-- Investment Banks
(
  'JPMorgan Chase', 
  'https://www.linkedin.com/company/jpmorganchase/',
  'https://logo.clearbit.com/jpmorganchase.com',
  'Investment Banking',
  293000,
  245,
  3.9,
  8.5,
  'United States',
  'Global leader in investment banking, financial services for consumers and businesses, financial transaction processing, and asset management.',
  'To be the best financial services company in the world, helping clients achieve their goals and making a positive impact on communities.',
  ARRAY['Excellence', 'Integrity', 'Client Focus', 'Operational Excellence'],
  'Finance graduates with strong analytical skills, CFA candidates, experience in financial modeling and valuation. MBA preferred for senior roles.',
  '$85K-$180K (Analyst), $150K-$300K (Associate), $250K-$500K+ (VP+)'
),
(
  'Goldman Sachs',
  'https://www.linkedin.com/company/goldman-sachs/',
  'https://logo.clearbit.com/goldmansachs.com',
  'Investment Banking',
  45000,
  189,
  4.1,
  12.3,
  'United States',
  'Leading global investment banking, securities and investment management firm providing services to corporations, governments, and individuals.',
  'To advance sustainable economic growth and financial opportunity across the globe.',
  ARRAY['Client Service', 'Integrity', 'Excellence', 'Innovation'],
  'Top-tier university graduates, strong technical and analytical skills, CFA/CPA a plus. Demonstrated leadership and teamwork.',
  '$95K-$200K (Analyst), $175K-$350K (Associate), $300K-$600K+ (VP+)'
),
(
  'Morgan Stanley',
  'https://www.linkedin.com/company/morgan-stanley/',
  'https://logo.clearbit.com/morganstanley.com',
  'Investment Banking',
  80000,
  198,
  4.0,
  10.2,
  'United States',
  'Global financial services firm providing investment banking, securities, wealth management and investment management services.',
  'To give people, institutions and governments the confidence to reach further.',
  ARRAY['Putting Clients First', 'Doing the Right Thing', 'Leading with Exceptional Ideas', 'Giving Back'],
  'Strong academic background in finance/economics, excellent communication skills, ability to work in fast-paced environment.',
  '$90K-$185K (Analyst), $160K-$320K (Associate), $280K-$550K+ (VP+)'
),

-- Private Equity
(
  'Blackstone',
  'https://www.linkedin.com/company/blackstone/',
  'https://logo.clearbit.com/blackstone.com',
  'Private Equity',
  4700,
  87,
  4.3,
  15.8,
  'United States',
  'World''s largest alternative asset manager with expertise in real estate, private equity, hedge funds, and credit.',
  'To be the world''s leading investment firm, creating value for our clients, shareholders and the communities where we operate.',
  ARRAY['Excellence', 'Creativity', 'Entrepreneurship', 'Integrity'],
  '2-3 years investment banking experience, strong deal execution skills, MBA from top-tier school preferred.',
  '$150K-$250K (Associate), $300K-$500K (VP), $500K-$1M+ (Senior)'
),
(
  'KKR',
  'https://www.linkedin.com/company/kkr/',
  'https://logo.clearbit.com/kkr.com',
  'Private Equity',
  2100,
  62,
  4.2,
  14.5,
  'United States',
  'Global investment firm managing multiple alternative asset classes including private equity, energy, infrastructure, real estate and credit.',
  'To generate attractive returns for our fund investors by prudently managing their capital.',
  ARRAY['Partnership', 'Ownership', 'Integrity', 'Excellence'],
  'Investment banking or consulting background, strong analytical and modeling skills, entrepreneurial mindset.',
  '$140K-$240K (Associate), $280K-$480K (VP), $480K-$900K+ (Principal)'
),

-- Hedge Funds
(
  'Citadel',
  'https://www.linkedin.com/company/citadel/',
  'https://logo.clearbit.com/citadel.com',
  'Hedge Fund',
  2800,
  156,
  4.4,
  18.9,
  'United States',
  'Leading hedge fund managing capital across global equities, fixed income, commodities and quantitative strategies.',
  'To deliver superior risk-adjusted returns to our investors through disciplined investment processes.',
  ARRAY['Intellectual Rigor', 'Collaboration', 'Innovation', 'Excellence'],
  'Quantitative background (Math, Physics, CS, Engineering), strong programming skills (Python, C++), experience with financial markets.',
  '$150K-$300K (Analyst), $250K-$500K (Portfolio Manager), $500K-$2M+ (Senior PM)'
),
(
  'Bridgewater Associates',
  'https://www.linkedin.com/company/bridgewater-associates/',
  'https://logo.clearbit.com/bridgewater.com',
  'Hedge Fund',
  1500,
  43,
  3.8,
  9.2,
  'United States',
  'World''s largest hedge fund specializing in global macroeconomic investing and systematic trading strategies.',
  'To make a lot of money for our clients while being a great place to work.',
  ARRAY['Radical Transparency', 'Meaningful Work', 'Meaningful Relationships', 'Continuous Improvement'],
  'Economics or finance PhD preferred, deep understanding of macroeconomics, systematic thinking, comfort with intense feedback culture.',
  '$130K-$280K (Analyst), $220K-$450K (Investment Associate), $450K-$1.5M+ (Portfolio Strategist)'
),

-- FinTech
(
  'Stripe',
  'https://www.linkedin.com/company/stripe/',
  'https://logo.clearbit.com/stripe.com',
  'FinTech',
  7000,
  198,
  4.5,
  18.7,
  'United States',
  'Technology company building economic infrastructure for the internet, enabling online payment processing for businesses of all sizes.',
  'To increase the GDP of the internet by making it easy for businesses to accept payments and manage their operations online.',
  ARRAY['Users First', 'Move Fast', 'Think Rigorously', 'Trust by Default'],
  'Technical background in CS/Engineering, product management experience, understanding of payments infrastructure.',
  '$120K-$200K (Product Manager), $180K-$320K (Engineering Manager), $250K-$450K (Director+)'
),
(
  'Coinbase',
  'https://www.linkedin.com/company/coinbase/',
  'https://logo.clearbit.com/coinbase.com',
  'FinTech',
  3700,
  134,
  3.6,
  16.4,
  'United States',
  'Leading cryptocurrency exchange platform providing secure buying, selling, transferring, and storing of digital currency.',
  'To create an open financial system for the world and be the leading global brand for helping people convert digital currency into local currency.',
  ARRAY['Clear Communication', 'Efficient Execution', 'Act Like an Owner', 'Top Talent'],
  'Interest in crypto/blockchain technology, technical or finance background, comfortable with regulatory complexity.',
  '$110K-$190K (Analyst), $160K-$280K (Senior), $220K-$400K (Lead/Principal)'
),
(
  'Robinhood',
  'https://www.linkedin.com/company/robinhood/',
  'https://logo.clearbit.com/robinhood.com',
  'FinTech',
  3400,
  92,
  3.8,
  13.6,
  'United States',
  'Commission-free stock trading and investing app democratizing finance for all, offering stocks, ETFs, options, and cryptocurrency.',
  'To democratize finance for all by making investing accessible and affordable.',
  ARRAY['Safety First', 'Radical Customer Focus', 'First-Principles Thinking', 'Ownership'],
  'Finance or tech background, product/engineering experience, passion for democratizing investing.',
  '$100K-$180K (Product Manager), $150K-$270K (Engineering), $200K-$380K (Director+)'
),

-- Asset Management
(
  'BlackRock',
  'https://www.linkedin.com/company/blackrock/',
  'https://logo.clearbit.com/blackrock.com',
  'Asset Management',
  19800,
  287,
  4.0,
  11.7,
  'United States',
  'World''s largest asset manager providing investment management, risk management and advisory services to institutional and retail clients.',
  'To help more and more people experience financial well-being.',
  ARRAY['Fiduciary', 'Passionate About Performance', 'Client-Centric', 'One BlackRock'],
  'CFA charterholder or progress toward, strong quantitative skills, experience in portfolio management or investment analysis.',
  '$95K-$175K (Analyst), $150K-$280K (Portfolio Manager), $250K-$500K+ (Managing Director)'
),
(
  'Vanguard',
  'https://www.linkedin.com/company/vanguard/',
  'https://logo.clearbit.com/vanguard.com',
  'Asset Management',
  17600,
  213,
  4.1,
  10.8,
  'United States',
  'Investment management company offering low-cost mutual funds, ETFs, and retirement investment products to individual investors.',
  'To take a stand for all investors, to treat them fairly, and to give them the best chance for investment success.',
  ARRAY['Client-Focused', 'Integrity', 'Excellence', 'Stewardship'],
  'Strong analytical background, CFA preferred, commitment to low-cost index investing philosophy.',
  '$80K-$150K (Analyst), $130K-$240K (Senior Analyst), $200K-$400K (Principal)'
),

-- Consulting
(
  'McKinsey & Company',
  'https://www.linkedin.com/company/mckinsey/',
  'https://logo.clearbit.com/mckinsey.com',
  'Management Consulting',
  45000,
  523,
  4.3,
  14.2,
  'United States',
  'Global management consulting firm advising leading businesses, governments, and institutions on strategy, operations, and transformation.',
  'To help create positive, enduring change in the world.',
  ARRAY['Client Impact', 'Inclusive Community', 'Courageous Change', 'Sustained Partnerships'],
  'Top MBA or PhD, exceptional problem-solving skills, 2+ years pre-MBA experience in finance, consulting, or strategy.',
  '$90K-$165K (Business Analyst), $175K-$220K (Associate), $250K-$450K (Engagement Manager+)'
),
(
  'Boston Consulting Group',
  'https://www.linkedin.com/company/boston-consulting-group/',
  'https://logo.clearbit.com/bcg.com',
  'Management Consulting',
  32000,
  478,
  4.2,
  13.9,
  'United States',
  'Global management consulting firm partnering with business and society leaders to tackle complex challenges and seize opportunities.',
  'To unlock the potential of those who advance the world.',
  ARRAY['Impact', 'Curiosity', 'Diversity', 'Openness', 'Respect'],
  'Advanced degree (MBA, PhD) or exceptional undergraduate, strong quantitative and analytical skills, global mindset.',
  '$85K-$155K (Associate), $165K-$210K (Consultant), $240K-$420K (Project Leader+)'
),

-- Venture Capital
(
  'Sequoia Capital',
  'https://www.linkedin.com/company/sequoia-capital/',
  'https://logo.clearbit.com/sequoiacap.com',
  'Venture Capital',
  180,
  12,
  4.6,
  8.3,
  'United States',
  'Leading venture capital firm partnering with bold entrepreneurs to build legendary companies across technology and healthcare sectors.',
  'To help the daring build legendary companies that make a positive impact on the world.',
  ARRAY['Partnership', 'Long-term Thinking', 'Founder-First', 'Excellence'],
  'Investment banking, PE, or operating experience at startups, strong network in tech ecosystem, MBA from top school.',
  '$150K-$250K (Associate), $250K-$400K (Principal), $400K-$800K+ (Partner)'
),
(
  'Andreessen Horowitz',
  'https://www.linkedin.com/company/andreessen-horowitz/',
  'https://logo.clearbit.com/a16z.com',
  'Venture Capital',
  520,
  34,
  4.4,
  12.7,
  'United States',
  'Venture capital firm backing bold entrepreneurs building the future through technology, from seed to growth stage.',
  'To back the entrepreneurs shaping the future through technology.',
  ARRAY['Respect for the Entrepreneur', 'Trust', 'Humility', 'Transparency'],
  'Operating experience at tech companies strongly preferred, product or engineering background, understanding of emerging tech trends.',
  '$140K-$240K (Associate), $240K-$380K (Principal), $380K-$750K+ (General Partner)'
),

-- Global Banks
(
  'HSBC',
  'https://www.linkedin.com/company/hsbc/',
  'https://logo.clearbit.com/hsbc.com',
  'Investment Banking',
  220000,
  312,
  3.8,
  7.9,
  'EMEA',
  'Global banking and financial services organization serving millions of customers through retail banking, wealth management, and commercial banking.',
  'Opening up a world of opportunity for our customers, colleagues, and communities.',
  ARRAY['Dependable', 'Open', 'Connected', 'Customer-First'],
  'International mindset, language skills a plus, experience in global markets, regulatory knowledge.',
  '£50K-£90K (Analyst), £80K-£150K (Associate), £140K-£280K (VP+)'
),
(
  'Barclays',
  'https://www.linkedin.com/company/barclays/',
  'https://logo.clearbit.com/barclays.com',
  'Investment Banking',
  85000,
  267,
  3.9,
  9.4,
  'EMEA',
  'British universal bank offering retail banking, credit cards, corporate banking, investment banking, and wealth management services globally.',
  'To be the UK-centered leader in global finance, helping customers succeed and communities thrive.',
  ARRAY['Respect', 'Integrity', 'Service', 'Excellence', 'Stewardship'],
  'Strong academic background, European markets knowledge, ability to work across cultures and time zones.',
  '£55K-£95K (Analyst), £90K-£165K (Associate), £150K-£300K (VP+)'
),

-- Insurance/Financial Services
(
  'Swiss Re',
  'https://www.linkedin.com/company/swiss-re/',
  'https://logo.clearbit.com/swissre.com',
  'Insurance & Reinsurance',
  14500,
  124,
  4.1,
  8.7,
  'EMEA',
  'Leading wholesale provider of reinsurance, insurance and other insurance-based forms of risk transfer, managing risk and capital.',
  'To make the world more resilient by anticipating and managing risk.',
  ARRAY['Collaboration', 'Accountability', 'Forward-Thinking', 'Inclusive'],
  'Actuarial background or strong quantitative skills, risk modeling experience, understanding of insurance markets.',
  'CHF 85K-CHF 140K (Analyst), CHF 130K-CHF 220K (Manager), CHF 200K-CHF 400K+ (Director+)'
),
(
  'Allianz',
  'https://www.linkedin.com/company/allianz/',
  'https://logo.clearbit.com/allianz.com',
  'Insurance & Asset Management',
  157000,
  421,
  3.9,
  9.1,
  'EMEA',
  'Leading global insurer and asset manager providing property-casualty insurance, life/health insurance, and asset management to customers worldwide.',
  'We secure your future - empowering people to live their best lives.',
  ARRAY['Passion', 'Excellence', 'Respect', 'Accountability'],
  'Insurance or investment management background, multilingual capabilities valued, certifications (CFA, FRM) beneficial.',
  '€60K-€110K (Analyst), €100K-€180K (Senior Manager), €170K-€350K (Director+)'
)
ON CONFLICT (id) DO NOTHING;